name: AlchemicalCauldron
main: com.github.Indiv0.AlchemicalCauldron.AlchemicalCauldron
version: 1.3.2
author: Indiv0
description: A plugin for using the AlchemicalCauldron to convert items.
dev-url: http://github.com/Indiv0/AlchemicalCauldron/

permissions:
  alchemicalcauldron.*:
    description: Controls all AlchemicalCauldron permissions
    children:
      alchemicalcauldron.all: true
  alchemicalcauldron.use:
    description: Controls whether or not the user can use AlchemicalCauldron
    default: true