name: AlchemicalCauldron
main: in.nikitapek.alchemicalcauldron.AlchemicalCauldronPlugin
load: POSTWORLD
version: ${project.version}
author: Indiv0
description: A plugin for using the AlchemicalCauldron to convert items.
dev-url: http://github.com/Indiv0/AlchemicalCauldron/

permissions:
  alchemicalcauldron.*:
    description: Controls all AlchemicalCauldron permissions
    children:
      alchemicalcauldron.use: true
  alchemicalcauldron.use:
    description: Controls whether or not the user can use AlchemicalCauldron
    default: true
